FROM python:3.11.9-bullseye AS base
ARG DEBIAN_FRONTEND=noninteractive

# Install base dependencies
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    git \
    cmake \
    apt-transport-https \
    software-properties-common \
    ca-certificates \
    libc6-i386 \
    libc6-x32 \
    libxtst6
RUN rm -rf /var/lib/apt/lists/*

# Install pipx
RUN pip3 install pipx
ENV PATH="/root/.local/bin:$PATH"

# Install GDAL
RUN apt-get update && apt-get install -y libproj-dev gdal-bin

# Install Imagemagick
RUN apt-get update && apt-get install -y imagemagick
COPY config/imagemagick_policy.xml /etc/ImageMagick-6/policy.xml

# Install LibreOffice
RUN apt-get update && apt-get install -y libreoffice

# Install GhostScript
RUN apt-get update && apt-get install -y ghostscript

# Install ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Install chrome
WORKDIR /root
RUN curl -L https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /root/google-chrome-stable_current_amd64.deb
RUN apt-get update && apt-get install -y /root/google-chrome-stable_current_amd64.deb
RUN ln -s $(which google-chrome-stable) /usr/bin/chrome
RUN rm google-chrome-stable_current_amd64.deb

# Install QCAD
WORKDIR /root
RUN mkdir -p /root/qcad
RUN curl https://qcad.org/archives/qcad/qcadcam-3.28.2-trial-linux-x86_64.run -o /root/qcad/qcad-installer.run
RUN chmod a+x /root/qcad/qcad-installer.run
RUN /root/qcad/qcad-installer.run
RUN rm -rf /root/qcad

CMD ["bash"]