FROM python:3.11.9-bullseye as base
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y curl wget git cmake
RUN rm -rf /var/lib/apt/lists/*

# Install pipx
RUN pip3 install pipx

# Install GDAL
RUN apt-get update && apt-get install -y libproj-dev
RUN wget https://github.com/OSGeo/gdal/releases/download/v3.5.2/gdal-3.5.2.tar.gz && tar -xzf gdal-3.5.2.tar.gz
WORKDIR "/gdal-3.5.2/build"
RUN cmake .. && cmake --build . && cmake --build . --target install
WORKDIR "/"

# Install GhostScript
# We must update apt-get again for else GhostScript won't install
RUN apt-get update && apt-get install -y ghostscript libreoffice ffmpeg imagemagick libc6-i386 libc6-x32 libxtst6

## Install JDK
RUN wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb && dpkg -i jdk-17_linux-x64_bin.deb
ENV PATH "${PATH}:/usr/lib/jvm/jdk-17/bin"

# Install chrome
RUN curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
RUN apt update -y && apt install -y google-chrome-stable
RUN ln -s $(which google-chrome-stable) /usr/bin/chrome

# Install QCAD
WORKDIR /root
RUN mkdir -p /root/qcad
RUN curl https://qcad.org/archives/qcad/qcadcam-3.28.1-trial-linux-x86_64.run -o /root/qcad/qcadcam-3.28.1-trial-linux-x86_64.run
RUN chmod a+x /root/qcad/qcadcam-3.28.1-trial-linux-x86_64.run
RUN /root/qcad/qcadcam-3.28.1-trial-linux-x86_64.run