name: Develop

on: [push]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install & set up poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
          poetry config virtualenvs.in-project true
      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Install dependencies
        run: |
          source $HOME/.poetry/env
          poetry install
      - name: Install flake8
        run: |
          pip install flake8 --quiet
      - name: Check linting
        run: |
          source $HOME/.poetry/env
          flake8 --exclude .venv
        # poetry run black --check .
      - name: Run mypy
        run: |
          source $HOME/.poetry/env
          poetry run mypy
      # - name: Run prospector
      #   run: |
      #     source $HOME/.poetry/env
      #     poetry run prospector -M -i .venv/
  # check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout 
  #       uses: actions/checkout@v1
  #     - name: Set up Python 3.7
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.7
  #     - name: Install tools
  #       run: pip install mypy prospector --quiet
  #     - name: Run mypy
  #       run: |
  #         mypy convertool/
  #         mypy tests/
  #     - name: Run prospector
  #       run: |
  #         prospector -M

