name: Develop

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install & run flake8
        run: |
          pip install flake8 --quiet
          flake8 convertool/
          flake8 tests/
      - name: Install & run black
        run: |
          pip install black --quiet
          black --check convertool/
          black --check tests/
      - name: Install & run mypy
        run: |
          pip install mypy --quiet
          mypy convertool/
          mypy tests/
      - name: Install & run prospector
        run: |
          pip install prospector --quiet
          prospector -M

