name: "Build Base Image"

on:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile-base"
  workflow_dispatch:

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Date Tag
        id: date
        run: echo "date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login To Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.openaws.dk
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            git.openaws.dk/aarhusstadsarkiv/convertool-base:latest
            git.openaws.dk/aarhusstadsarkiv/convertool-base:${{ steps.date.outputs.date }}
          file: Dockerfile-base
          cache-from: type=gha
          cache-to: type=gha,mode=max