name: Linting & Test

on:
  push:
    paths:
      - convertool/**
      - config/**
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11.5
  POETRY_VERSION: 1.6.1

jobs:
  linting:
    name: Check Linting & Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - run: poetry install
      - name: ruff check
        run: poetry run ruff check convertool
      - name: ruff format
        run: poetry run ruff format --check convertool

  version:
    name: Test Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          project_name="$(grep --color=never 'name *= *".*"' pyproject.toml)"
          project_name="${project_name%\"}"
          project_name="${project_name#*\"}"
          version_project="$(grep --color=never 'version *= *".*"' pyproject.toml)"
          version_project="${version_project%\"}"
          version_project="${version_project#*\"}"
          version_package="$(grep --color=never '__version__ *= *".*"' "$project_name"/__version__.py)"
          version_package="${version_package%\"}"
          version_package="${version_package#*\"}"
          test "$version_project" = "$version_package"

  version-acacore:
    name: Test acacore Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Fetch Acacore Version
        run: |
          acacore_remote="$(python -c 'import urllib.request,json;print(json.loads(urllib.request.urlopen("https://api.github.com/repos/aarhusstadsarkiv/acacore/tags").read())[0]["name"])')"
          acacore_remote="${acacore_remote#v}"
          acacore_package="$(grep 'acacore =' pyproject.toml | grep -oE 'tag[ ]*=[ ]*"[^"]+"')"
          acacore_package="${acacore_package#*\"}"
          acacore_package="${acacore_package#v}"
          acacore_package="${acacore_package%\"}"
          test "$acacore_remote" = "$acacore_package"

  pytest:
    name: pytest
    runs-on: ubuntu-latest
    needs:
      - linting
      - version
      - version-acacore
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          target: test
          tags: convertool:latest
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run tests and report coverage
        run: |
          docker run -v $(pwd):/root/convertool convertool:latest poetry run pytest --cov-report=term:skip-covered --cov-fail-under=80 --cov=convertool tests/
      
