name: Test

on:
  push:
    paths:
      - convertool/**
      - config/**
      - tests/**
      - Dockerfile
      - Dockerfile-base
      - pyproject.toml
      - poetry.lock
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11.9
  POETRY_VERSION: 1.8.3

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Base Image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-base
          context: .
          target: base
          platforms: linux/amd64
          tags: convertool-base:latest
          push: false
          load: true
      - name: Build Test Target
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          target: test
          platforms: linux/amd64
          tags: convertool:latest
          push: false
          pull: false
          load: true
      - name: Run tests and report coverage
        run: |
          docker run -v $(pwd):/root/convertool convertool:latest poetry run coverage run -m pytest
          docker run -v $(pwd):/root/convertool convertool:latest poetry run coverage report -m --fail-under=80 --skip-empty --skip-covered
