name: Test

on:
  push:
    paths:
      - convertool/**
      - config/**
      - tests/**
      - Dockerfile
      - Dockerfile-base
      - pyproject.toml
      - poetry.lock
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11.9
  POETRY_VERSION: 1.8.3

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - run: poetry install
      - name: ruff check
        run: poetry run ruff check convertool
      - name: ruff format
        run: poetry run ruff format --check convertool

  version:
    name: Test Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          project_name="$(grep --color=never 'name *= *".*"' pyproject.toml)"
          project_name="${project_name%\"}"
          project_name="${project_name#*\"}"
          version_project="$(grep --color=never 'version *= *".*"' pyproject.toml)"
          version_project="${version_project%\"}"
          version_project="${version_project#*\"}"
          version_package="$(grep --color=never '__version__ *= *".*"' "$project_name"/__version__.py)"
          version_package="${version_package%\"}"
          version_package="${version_package#*\"}"
          test "$version_project" = "$version_package"

  version-acacore:
    name: Test acacore Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Acacore Version
        run: |
          acacore_remote="$(python -c 'import urllib.request,json;print(json.loads(urllib.request.urlopen("https://api.github.com/repos/aarhusstadsarkiv/acacore/tags").read())[0]["name"])')"
          acacore_remote="${acacore_remote#v}"
          acacore_package="$(grep 'acacore =' pyproject.toml | grep -oE 'tag[ ]*=[ ]*"[^"]+"')"
          acacore_package="${acacore_package#*\"}"
          acacore_package="${acacore_package#v}"
          acacore_package="${acacore_package%\"}"
          test "$acacore_remote" = "$acacore_package"

  pytest:
    name: pytest
    runs-on: ubuntu-latest
    needs:
      - linting
      - version
      - version-acacore
    steps:
      - uses: actions/checkout@v4
      - name: Build Base Image
        run: docker build . -t convertool-base:latest -f Dockerfile-base
      - name: Build Test Target
        run: docker build . -t convertool:latest -f Dockerfile-base
      - name: Run tests and report coverage
        run: |
          docker run -v $(pwd):/root/convertool convertool:latest poetry run coverage run -m pytest
          docker run -v $(pwd):/root/convertool convertool:latest poetry run coverage report -m --fail-under=80 --skip-empty --skip-covered
